export const ADMIN_USER_ALL_STATUS = "ALL";
export const ADMIN_USER_DEFAULT_SORTING = [{ id: "id", desc: true }];

export function mapAdminUserSortingToApiQuery(sorting) {
  const primarySort = sorting[0];
  const sortMap = {
    id: "id",
    username: "username",
    email: "email",
    userType: "userType",
    status: "status",
    createdAt: "createdAt",
    updatedAt: "updatedAt",
    lastLoginAt: "lastLoginAt",
    lastSeenAt: "lastSeenAt",
  };

  return {
    sortBy: sortMap[primarySort?.id] ?? "id",
    sortOrder: primarySort?.desc === false ? "asc" : "desc",
  };
}

export function getAdminUserText(lang, t) {
  return {
    id: "ID",
    username: lang === "km" ? "ឈ្មោះគណនី" : "Username",
    fullName: lang === "km" ? "ឈ្មោះពេញ" : "Full Name",
    firstName: lang === "km" ? "នាមខ្លួន" : "First Name",
    lastName: lang === "km" ? "នាមត្រកូល" : "Last Name",
    email: "Email",
    phoneNumber: lang === "km" ? "លេខទូរស័ព្ទ" : "Phone Number",
    userType: lang === "km" ? "ប្រភេទអ្នកប្រើ" : "User Type",
    status: lang === "km" ? "ស្ថានភាព" : "Status",
    temporaryPassword: lang === "km" ? "ពាក្យសម្ងាត់បណ្តោះអាសន្ន" : "Temporary Password",
    password: lang === "km" ? "ពាក្យសម្ងាត់" : "Password",
    newPassword: lang === "km" ? "ពាក្យសម្ងាត់ថ្មី" : "New Password",
    newPasswordHint: lang === "km"
      ? "យ៉ាងហោចណាស់ 8 តួអក្សរ មានអក្សរតូច អក្សរធំ លេខ អក្សរពិសេស និងគ្មានដកឃ្លា។"
      : "At least 8 characters with uppercase, lowercase, number, special character, and no spaces.",
    passwordValidationMessage: lang === "km"
      ? "ពាក្យសម្ងាត់ត្រូវមាន 8-128 តួអក្សរ មានអក្សរតូច អក្សរធំ លេខ អក្សរពិសេស និងគ្មានដកឃ្លា។"
      : "Password must be 8-128 characters and include uppercase, lowercase, number, special character, and no spaces.",
    lastLoginAt: lang === "km" ? "ចូលចុងក្រោយ" : "Last Login",
    lastSeenAt: lang === "km" ? "ឃើញចុងក្រោយ" : "Last Seen",
    createdAt: lang === "km" ? "បង្កើតនៅ" : "Created At",
    users: lang === "km" ? "ការគ្រប់គ្រងអ្នកប្រើ" : "User Management",
    addUser: lang === "km" ? "បន្ថែមអ្នកប្រើថ្មី" : "Add new user",
    editUser: lang === "km" ? "កែប្រែអ្នកប្រើ" : "Edit user",
    create: lang === "km" ? "បង្កើត" : "Create",
    update: lang === "km" ? "ធ្វើបច្ចុប្បន្នភាព" : "Update",
    edit: t.edit || "Edit",
    softDelete: lang === "km" ? "លុបទន់" : "Soft Delete",
    hardDelete: lang === "km" ? "លុបអចិន្រ្តៃយ៍" : "Hard Delete",
    close: lang === "km" ? "បិទ" : "Close",
    actions: lang === "km" ? "សកម្មភាព" : "Actions",
    searchPlaceholder: lang === "km" ? "ស្វែងរកអ្នកប្រើ" : "Search users",
    emptyMessage: lang === "km" ? "មិនមានអ្នកប្រើត្រូវនឹងការស្វែងរកនេះទេ។" : "No users match this search.",
    filterAllStatuses: lang === "km" ? "ស្ថានភាពទាំងអស់" : "All statuses",
    filterDeleted: lang === "km" ? "បានលុប" : "Deleted",
    userTypeCustomer: lang === "km" ? "អតិថិជន" : "Customer",
    userTypeProvider: lang === "km" ? "អ្នកផ្តល់សេវា" : "Provider",
    userTypeAdmin: lang === "km" ? "អ្នកគ្រប់គ្រង" : "Admin",
    requestFailed: lang === "km" ? "សំណើបានបរាជ័យ។ សូមព្យាយាមម្តងទៀត។" : "Request failed. Please try again.",
    validationRequired: lang === "km" ? "សូមបំពេញវាលនេះ។" : "This field is required.",
    deleteTitle: lang === "km" ? "បញ្ជាក់ការលុប" : "Confirm soft delete",
    deleteConfirm: lang === "km" ? "តើអ្នកពិតជាចង់លុបអ្នកប្រើនេះមែនទេ?" : "Are you sure you want to soft delete this user?",
    hardDeleteTitle: lang === "km" ? "បញ្ជាក់ការលុបអចិន្រ្តៃយ៍" : "Confirm hard delete",
    hardDeleteConfirm: lang === "km" ? "តើអ្នកពិតជាចង់លុបអ្នកប្រើនេះជាអចិន្រ្តៃយ៍មែនទេ?" : "Are you sure you want to permanently delete this user?",
    statusActive: t.active || "Active",
    statusSuspended: lang === "km" ? "ផ្អាក" : "Suspended",
    statusDeleted: lang === "km" ? "បានលុប" : "Deleted",
    toastSuccessTitle: lang === "km" ? "ជោគជ័យ" : "Success",
    toastErrorTitle: lang === "km" ? "បរាជ័យ" : "Error",
    toastCreateSuccess: lang === "km" ? "បានបង្កើតអ្នកប្រើថ្មីដោយជោគជ័យ។" : "User created successfully.",
    toastUpdateSuccess: lang === "km" ? "បានកែប្រែអ្នកប្រើដោយជោគជ័យ។" : "User updated successfully.",
    toastPasswordSuccess: lang === "km" ? "បានផ្លាស់ប្តូរពាក្យសម្ងាត់ដោយជោគជ័យ។" : "Password updated successfully.",
    toastSoftDeleteSuccess: lang === "km" ? "បានលុបអ្នកប្រើដោយជោគជ័យ។" : "User soft deleted successfully.",
    toastHardDeleteSuccess: lang === "km" ? "បានលុបអ្នកប្រើជាអចិន្រ្តៃយ៍ដោយជោគជ័យ។" : "User permanently deleted successfully.",
  };
}

export function getAdminCustomerText(lang, t) {
  return {
    id: "ID",
    customer: lang === "km" ? "អតិថិជន" : "Customer",
    customerManagement: lang === "km" ? "ការគ្រប់គ្រងអតិថិជន" : "Customer Management",
    addCustomer: lang === "km" ? "បន្ថែមអតិថិជនថ្មី" : "Add new customer",
    editCustomer: lang === "km" ? "កែប្រែអតិថិជន" : "Edit customer",
    userId: lang === "km" ? "លេខសម្គាល់អ្នកប្រើ" : "User ID",
    email: "Email",
    emailSearchPlaceholder: lang === "km" ? "ស្វែងរកដោយអ៊ីមែល" : "Search by email",
    matchingUsers: lang === "km" ? "អ្នកប្រើដែលត្រូវគ្នា" : "Matching users",
    noMatchingUsers: lang === "km" ? "មិនមានអ្នកប្រើត្រូវគ្នាទេ។" : "No matching users found.",
    searching: lang === "km" ? "កំពុងស្វែងរក..." : "Searching...",
    selected: lang === "km" ? "បានជ្រើសរើស" : "Selected",
    username: lang === "km" ? "ឈ្មោះគណនី" : "Username",
    bio: lang === "km" ? "ជីវប្រវត្តិ" : "Bio",
    dob: lang === "km" ? "ថ្ងៃខែឆ្នាំកំណើត" : "Date of Birth",
    gender: lang === "km" ? "ភេទ" : "Gender",
    genderMale: lang === "km" ? "ប្រុស" : "Male",
    genderFemale: lang === "km" ? "ស្រី" : "Female",
    preferredLanguage: lang === "km" ? "ភាសាដែលចូលចិត្ត" : "Preferred Language",
    onboardingCompleted: lang === "km" ? "បញ្ចប់ការចាប់ផ្តើម" : "Onboarding Completed",
    yes: lang === "km" ? "បាទ/ចាស" : "Yes",
    no: lang === "km" ? "ទេ" : "No",
    createdAt: lang === "km" ? "បង្កើតនៅ" : "Created At",
    create: lang === "km" ? "បង្កើត" : "Create",
    update: lang === "km" ? "ធ្វើបច្ចុប្បន្នភាព" : "Update",
    edit: t.edit || "Edit",
    delete: lang === "km" ? "លុប" : "Delete",
    close: lang === "km" ? "បិទ" : "Close",
    actions: lang === "km" ? "សកម្មភាព" : "Actions",
    searchPlaceholder: lang === "km" ? "ស្វែងរកអតិថិជន" : "Search customers",
    emptyMessage: lang === "km" ? "មិនមានអតិថិជនត្រូវនឹងការស្វែងរកនេះទេ។" : "No customers match this search.",
    filterAllStatuses: lang === "km" ? "ស្ថានភាពទាំងអស់" : "All statuses",
    filterDeleted: lang === "km" ? "បានលុប" : "Deleted",
    requestFailed: lang === "km" ? "សំណើបានបរាជ័យ។ សូមព្យាយាមម្តងទៀត។" : "Request failed. Please try again.",
    validationRequired: lang === "km" ? "សូមបំពេញវាលនេះ។" : "This field is required.",
    deleteTitle: lang === "km" ? "បញ្ជាក់ការលុប" : "Confirm soft delete",
    deleteConfirm: lang === "km" ? "តើអ្នកពិតជាចង់លុបអតិថិជននេះមែនទេ?" : "Are you sure you want to soft delete this customer?",
    hardDelete: lang === "km" ? "លុបអចិន្រ្តៃយ៍" : "Hard Delete",
    hardDeleteTitle: lang === "km" ? "បញ្ជាក់ការលុបអចិន្រ្តៃយ៍" : "Confirm hard delete",
    hardDeleteConfirm: lang === "km" ? "តើអ្នកពិតជាចង់លុបអតិថិជននេះជាអចិន្រ្តៃយ៍មែនទេ?" : "Are you sure you want to permanently delete this customer?",
    toastSuccessTitle: lang === "km" ? "ជោគជ័យ" : "Success",
    toastErrorTitle: lang === "km" ? "បរាជ័យ" : "Error",
    toastCreateSuccess: lang === "km" ? "បានបង្កើតអតិថិជនថ្មីដោយជោគជ័យ។" : "Customer created successfully.",
    toastUpdateSuccess: lang === "km" ? "បានកែប្រែអតិថិជនដោយជោគជ័យ។" : "Customer updated successfully.",
    toastPasswordSuccess: lang === "km" ? "បានផ្លាស់ប្តូរពាក្យសម្ងាត់ដោយជោគជ័យ។" : "Password updated successfully.",
    toastDeleteSuccess: lang === "km" ? "បានលុបអតិថិជនជាអចិន្រ្តៃយ៍ដោយជោគជ័យ។" : "Customer permanently deleted successfully.",
  };

}

export function getAdminProviderText(lang, t) {
  return {
    id: "ID",
    provider: lang === "km" ? "អ្នកផ្តល់សេវា" : "Provider",
    providerManagement: lang === "km" ? "ការគ្រប់គ្រងអ្នកផ្តល់សេវា" : "Provider Management",
    addProvider: lang === "km" ? "បន្ថែមអ្នកផ្តល់សេវាថ្មី" : "Add new provider",
    editProvider: lang === "km" ? "កែប្រែអ្នកផ្តល់សេវា" : "Edit provider",
    image: lang === "km" ? "រូបភាព" : "Image",
    uploadAvatar: lang === "km" ? "បង្ហោះរូបប្រវត្តិ" : "Avatar",
    imageUploadTitle: lang === "km" ? "បង្ហោះរូបអ្នកផ្តល់សេវា" : "Upload provider image",
    imageUploadHint: lang === "km" ? "ជ្រើសរូបភាពថ្មីសម្រាប់រូបប្រវត្តិអ្នកផ្តល់សេវា។" : "Choose a new image for this provider avatar.",
    imageUploadFormats: lang === "km" ? "ប្រភេទឯកសារ JPG, PNG, ឬ WEBP មានទំហំតិចជាង 8MB។" : "Use JPG, PNG, or WEBP files up to 8MB.",
    noImageSelected: lang === "km" ? "មិនទាន់មានរូបភាព" : "No image selected.",
    validationImageRequired: lang === "km" ? "សូមជ្រើសរើសរូបភាពមុននឹងបង្ហោះ។" : "Please choose an image before uploading.",
    validationImageFileType: lang === "km" ? "សូមប្រើតែឯកសារ JPG, PNG, ឬ WEBP ប៉ុណ្ណោះ។" : "Please use JPG, PNG, or WEBP files only.",
    validationImageFileSize: lang === "km" ? "ទំហំរូបភាពត្រូវតែតិចជាង 8MB។" : "Image size must be under 8MB.",
    validationImageFileRead: lang === "km" ? "មិនអាចអានឯកសាររូបភាពនេះបានទេ។" : "Unable to read this image file.",
    changeProviderStatus: lang === "km" ? "ប្តូរស្ថានភាពអ្នកផ្តល់សេវា" : "Change provider status",
    email: "Email",
    emailSearchPlaceholder: lang === "km" ? "ស្វែងរកដោយអ៊ីមែល" : "Search by email",
    matchingUsers: lang === "km" ? "អ្នកប្រើដែលត្រូវគ្នា" : "Matching users",
    noMatchingUsers: lang === "km" ? "មិនមានអ្នកប្រើត្រូវគ្នាទេ។" : "No matching users found.",
    searching: lang === "km" ? "កំពុងស្វែងរក..." : "Searching...",
    selected: lang === "km" ? "បានជ្រើសរើស" : "Selected",
    yes: lang === "km" ? "បាទ/ចាស" : "Yes",
    no: lang === "km" ? "ទេ" : "No",
    username: lang === "km" ? "ឈ្មោះគណនី" : "Username",
    firstName: lang === "km" ? "នាមខ្លួន" : "First Name",
    lastName: lang === "km" ? "នាមត្រកូល" : "Last Name",
    phoneNumber: lang === "km" ? "លេខទូរស័ព្ទ" : "Phone Number",
    userType: lang === "km" ? "ប្រភេទអ្នកប្រើ" : "User Type",
    userTypeCustomer: lang === "km" ? "អតិថិជន" : "Customer",
    userTypeProvider: lang === "km" ? "អ្នកផ្តល់សេវា" : "Provider",
    userTypeAdmin: lang === "km" ? "អ្នកគ្រប់គ្រង" : "Admin",
    password: lang === "km" ? "ពាក្យសម្ងាត់" : "Password",
    newPassword: lang === "km" ? "ពាក្យសម្ងាត់" : "Password",
    newPasswordHint: lang === "km"
      ? "យ៉ាងហោចណាស់ 8 តួអក្សរ មានអក្សរតូច អក្សរធំ លេខ អក្សរពិសេស និងគ្មានដកឃ្លា។"
      : "At least 8 characters with uppercase, lowercase, number, special character, and no spaces.",
    passwordValidationMessage: lang === "km"
      ? "ពាក្យសម្ងាត់ត្រូវមាន 8-128 តួអក្សរ មានអក្សរតូច អក្សរធំ លេខ អក្សរពិសេស និងគ្មានដកឃ្លា។"
      : "Password must be 8-128 characters and include uppercase, lowercase, number, special character, and no spaces.",
    bio: lang === "km" ? "ជីវប្រវត្តិ" : "Bio",
    businessName: lang === "km" ? "ឈ្មោះអាជីវកម្ម" : "Business Name",
    businessType: lang === "km" ? "ប្រភេទអាជីវកម្ម" : "Business Type",
    businessTypeCompany: lang === "km" ? "ក្រុមហ៊ុន" : "Company",
    businessTypeIndividual: lang === "km" ? "បុគ្គល" : "Individual",
    displayName: lang === "km" ? "ឈ្មោះដែលបានចូលចិត្ត" : "Display Name",
    establishedAt: lang === "km" ? "បង្កើតនៅ" : "Established At",
    telegram: lang === "km" ? "Telegram" : "Telegram",
    facebookUrl: lang === "km" ? "ហ្វេសប៊ុក" : "Facebook",
    status: lang === "km" ? "ស្ថានភាព" : "Status",
    providerStatusDraft: lang === "km" ? "ព្រាង" : "Draft",
    providerStatusPendingVerification: lang === "km" ? "កំពុងរង់ចាំការផ្ទៀងផ្ទាត់" : "Pending Verification",
    providerStatusRejected: lang === "km" ? "បដិសេធ" : "Rejected",
    providerStatusInactive: lang === "km" ? "មិនសកម្ម" : "Inactive",
    websiteUrl: lang === "km" ? "គេហទំព័រ" : "Website",
    createdAt: lang === "km" ? "បង្កើតនៅ" : "Created At",
    create: lang === "km" ? "បង្កើត" : "Create",
    update: lang === "km" ? "ធpreferredLanguage្វើបច្ចុប្បន្នភាព" : "Update",
    edit: t.edit || "Edit",
    delete: lang === "km" ? "លុប" : "Delete",
    close: lang === "km" ? "បិទ" : "Close",
    actions: lang === "km" ? "សកម្មភាព" : "Actions",
    searchPlaceholder: lang === "km" ? "ស្វែងរកអ្នកផ្គល់សេវា" : "Search provider",
    emptyMessage: lang === "km" ? "មិនមានអតិថិជនត្រូវនឹងការស្វែងរកនេះទេ។" : "No customers match this search.",
    filterAllStatuses: lang === "km" ? "ស្ថានភាពទាំងអស់" : "All statuses",
    filterDeleted: lang === "km" ? "បានលុប" : "Deleted",
    requestFailed: lang === "km" ? "សំណើបានបរាជ័យ។ សូមព្យាយាមម្តងទៀត។" : "Request failed. Please try again.",
    validationRequired: lang === "km" ? "សូមបំពេញវាលនេះ។" : "This field is required.",
    deleteTitle: lang === "km" ? "បញ្ជាក់ការលុប" : "Confirm soft delete",
    deleteConfirm: lang === "km" ? "តើអ្នកពិតជាចង់លុបអ្នកផ្តល់សេវានេះមែនទេ?" : "Are you sure you want to delete this provider?",
    toastSuccessTitle: lang === "km" ? "ជោគជ័យ" : "Success",
    toastErrorTitle: lang === "km" ? "បរាជ័យ" : "Error",
    toastCreateSuccess: lang === "km" ? "បានបង្កើតអ្នកផ្តល់សេវាថ្មីដោយជោគជ័យ។" : "Provider created successfully.",
    toastUpdateSuccess: lang === "km" ? "បានកែប្រែអ្នកផ្តល់សេវាដោយជោគជ័យ។" : "Provider updated successfully.",
    toastPasswordSuccess: lang === "km" ? "បានផ្លាស់ប្តូរពាក្យសម្ងាត់ដោយជោគជ័យ។" : "Password updated successfully.",
    toastDeleteSuccess: lang === "km" ? "បានលុបអ្នកផ្តល់សេវាដោយជោគជ័យ។" : "Provider deleted successfully.",
    statusActive: t.active || "Active",
    statusSuspended: lang === "km" ? "ផ្អាក" : "Suspended",
    statusDeleted: lang === "km" ? "បានលុប" : "Deleted",
  };

}
