/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'Battambang', 'system-ui', '-apple-system', 'Segoe UI', 'Roboto', 'Arial', 'sans-serif'],
        mono: ['Fira Code', 'Courier New', 'monospace'],
      },
      colors: {
        p: {
          50:  '#F6F2FF',
          100: '#EEE8FF',
          200: '#DED3FF',
          300: '#C6B0FF',
          400: '#A985FF',
          500: '#8B5CF6', 
          600: '#6D28D9',
          700: '#5B21B6',
          800: '#3B1A73',
          900: '#251042',
        },
        n: {
          0:   '#FFFFFF',
          50:  '#FAFAFB',
          100: '#F4F5F7',
          200: '#E6E8EE',
          300: '#D0D5DD',
          400: '#98A2B3',
          500: '#667085',
          700: '#344054',
          900: '#101828',
        },
        bg: {
          app: 'var(--bg-app)',
          surface: 'var(--bg-surface)',
          subtle: 'var(--bg-subtle)',
        },
        text: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          muted: 'var(--text-muted)',
          logo: 'var(--text-logo)',
        },
        border: {
          DEFAULT: 'var(--border-default)',
          strong: 'var(--border-strong)',
        },
        brand: {
          DEFAULT: 'var(--brand-primary)',
          hover: 'var(--brand-hover)',
          pressed: 'var(--brand-pressed)',
          soft: 'var(--brand-soft)',
        },
        focus: 'var(--focus-ring)',
        scrim: 'var(--scrim)',
        success: '#16A34A',
        warning: '#F59E0B',
        danger: '#DC2626',
        info: '#2563EB',
      },
      spacing: {
        0: '0px',
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
        12: '48px',
        16: '64px',
        20: '80px',
        24: '96px',
        32: '128px',
      },
      borderRadius: {
        sm: '8px',
        md: '10px',
        lg: '12px',
        xl: '16px',
        pill: '999px',
      },
      height: {
        sm: '32px',
        md: '40px',
        lg: '48px',
      },
      boxShadow: {
        1: 'var(--shadow-1)',
        2: 'var(--shadow-2)',
        3: 'var(--shadow-3)',
      },
      transitionTimingFunction: {
        smooth: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
      },
      transitionDuration: {
        fast: '120ms',
        base: '180ms',
        slow: '240ms',
      },
    },
  },
  plugins: [],
}
