export const SIGN_IN_TEXT = {
  en: {
    title: "Welcome Back",
    subtitle: "Sign in to continue your orders and bookings.",
    identifier: "Username or email",
    identifierPlaceholder: "provider.chantha or you@example.com",
    password: "Password",
    passwordPlaceholder: "Enter your password",
    weakPassword: "Password must be at least 8 characters and include upper, lower, number, and symbol.",
    rememberMe: "Remember me",
    invalidIdentifier: "Enter a valid username or email address.",
    requiredFields: "Username/email and password are required.",
    signInFailed: "Sign in failed. Please check your credentials and try again.",
    signingIn: "Signing in...",
    signInButton: "Sign in",
    forgotPassword: "Forgot password?",
    noAccount: "Don't have an account?",
    backHome: "Back to Home",
    highlightsTitle: "Why sign in?",
    highlightsOne: "Track your current and past orders",
    highlightsTwo: "Save your preferred providers",
    highlightsThree: "Get updates on booking status",
  },
  km: {
    title: "ស្វាគមន៍ការត្រឡប់មកវិញ",
    subtitle: "ចូលគណនីដើម្បីបន្តការកក់ និងការបញ្ជាទិញរបស់អ្នក។",
    identifier: "ឈ្មោះអ្នកប្រើប្រាស់ ឬ អ៊ីមែល",
    identifierPlaceholder: "provider.chantha ឬ you@example.com",
    password: "ពាក្យសម្ងាត់",
    passwordPlaceholder: "បញ្ចូលពាក្យសម្ងាត់",
    weakPassword: "ពាក្យសម្ងាត់ត្រូវមានយ៉ាងតិច 8 តួអក្សរ និងមានអក្សរធំ អក្សរតូច លេខ និងនិមិត្តសញ្ញា។",
    rememberMe: "ចងចាំខ្ញុំ",
    invalidIdentifier: "សូមបញ្ចូលឈ្មោះអ្នកប្រើប្រាស់ ឬ អ៊ីមែល ឱ្យត្រឹមត្រូវ។",
    requiredFields: "ឈ្មោះអ្នកប្រើប្រាស់/អ៊ីមែល និងពាក្យសម្ងាត់ ត្រូវបានទាមទារ។",
    signInFailed: "ការចូលគណនីមិនបានជោគជ័យទេ។ សូមពិនិត្យព័ត៌មានរបស់អ្នកម្តងទៀត។",
    signingIn: "កំពុងចូលគណនី...",
    signInButton: "ចូលគណនី",
    forgotPassword: "ភ្លេចពាក្យសម្ងាត់?",
    noAccount: "មិនទាន់មានគណនីទេ?",
    backHome: "ត្រឡប់ទៅទំព័រដើម",
    highlightsTitle: "អត្ថប្រយោជន៍ពេលចូលគណនី",
    highlightsOne: "តាមដានការបញ្ជាទិញ និងប្រវត្តិការកក់",
    highlightsTwo: "រក្សាទុកអ្នកផ្តល់សេវាដែលអ្នកពេញចិត្ត",
    highlightsThree: "ទទួលបានការជូនដំណឹងអំពីស្ថានភាពការកក់",
  },
};
